version: '3.3'

services:
  API:
    image: ${DOCKER_REGISTRY-}mc2crudtestserver
    build:
      context: .
      dockerfile: Presentation/SnowaTec.Test.API/Dockerfile
    ports: -5001:5001 -5002:5002
    depends_on:
      - db

  broker:
    image: ${DOCKER_REGISTRY-}mc2crudtestbroker
    build:
      context: .
      dockerfile: Presentation/SnowaTec.Test.Broker/Dockerfile
    ports: -5000:5000

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Bo!2bjaq
