version: '3.4'

services:
  snowatec.test.presentation.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5002;http://+:5001
    ports:
      - "5001:5001"
      - "5002:5002"
  snowatec.test.presentation.Front:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5004;http://+:5003
    ports:
      - "5003:5003"
      - "5004:5004"